name: mirror-images
on:
  schedule:
    - cron: '30 2 * * *'
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  images:
    name: Mirror Images
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3.0.0
    - name: Set OCF flag
      run: |
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes -c yes
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.3.0
    - name: Login to DockerHub
      uses: docker/login-action@v3.1.0
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Alpine 
      uses: docker/build-push-action@v5.3.0
      with:
        context: .
        file: ./alpine/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          flomesh/alpine:3
          flomesh/alpine:latest
    - name: Ubuntu-22.04 
      uses: docker/build-push-action@v5.3.0
      with:
        context: .
        file: ./ubuntu/22.04/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          flomesh/ubuntu:22.04
          
